"""empty message

Revision ID: 96a8ff8b6427
Revises: fd2455721d04
Create Date: 2022-11-23 17:22:58.051962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a8ff8b6427'
down_revision = 'fd2455721d04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
