"""add default value

Revision ID: fd2455721d04
Revises: 57e3e82e0251
Create Date: 2022-11-22 18:09:29.251266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2455721d04'
down_revision = '57e3e82e0251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'voted',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey', 'voted',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
